# Generated by Django 5.0.4 on 2024-04-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_names',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
