# Generated by Django 5.0.4 on 2024-04-15 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_first_name_patient_first_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_names',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
