# Generated by Django 5.0.4 on 2024-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_first_names_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=50),
        ),
    ]
