# Generated by Django 5.0.4 on 2024-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patient_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=1, max_length=50, verbose_name='vvedite vashe vozsart'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=120, verbose_name='vvedite vashe diagnoz'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='vvedite vashe familiyu'),
        ),
    ]
