# Generated by Django 5.0.4 on 2024-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patient_age_alter_patient_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default=1, max_length=50, verbose_name='vvedite vashe vozsart'),
        ),
    ]
