# Generated by Django 5.0.4 on 2024-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=50, verbose_name='vvedite vashe vozsart'),
        ),
    ]
