# Generated by Django 5.0.4 on 2024-04-17 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_patient_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='choosing_a_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='vyberite vashego vracha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(verbose_name='vvedite vashe vozsast'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=120, verbose_name='vvedite vash diagnoz'),
        ),
    ]
