# Generated by Django 5.0.4 on 2024-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patient_choosing_a_doctor_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='choosing_a_doctor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(verbose_name='vvedite vashe vozrast'),
        ),
    ]
