# Generated by Django 5.0.4 on 2024-04-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_age_alter_doctor_experience'),
        ('patients', '0016_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='choosing_a_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='doctors.doctor', verbose_name='vyberite vashego vracha'),
            preserve_default=False,
        ),
    ]
