# Generated by Django 5.0.4 on 2024-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_patient_age_alter_patient_disease_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
