# Generated by Django 5.0.4 on 2024-04-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_image_for_doctor_alter_doctor_lastname_and_more'),
        ('hospitals', '0002_rename_booking_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='choosing_a_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='vyberite vashego vracha'),
            preserve_default=False,
        ),
    ]
